modLoader="javafml" #mandatory
loaderVersion="[37, 38)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPL3"
[[mods]] #mandatory
modId="blockui" #mandatory
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="UI Library Mod" #mandatory
logoFile="" #optional
credits="LDT Team" #optional
authors="LDT Team" #optional
description='''
UI Library mod, use ctrl+alt+shift+x to open a test-ui
'''
[[dependencies.blockui]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37, 38)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.blockui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17, 1.18)"
    ordering="NONE"
    side="BOTH"