modLoader="javafml"
loaderVersion="${fmlRange}"
license="GPL 3.0"
issueTrackerURL="https://github.com/ldtteam/blockui/issues/new/choose"
[[mods]]
modId="blockui"
version="${version}"
displayName="UI Library Mod"
displayURL="https://minecolonies.com/"
logoFile=""
credits="LDT Team"
authors="LDT Team"
description='''
UI Library mod, use /blockui test to open a test-ui
'''

[[dependencies.blockui]]
    modId="forge"
    mandatory=true
    versionRange="${forgeRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.blockui]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftRange}"
    ordering="NONE"
    side="BOTH"
